### ISSUE TITLE
Get seasonally adjusted series in as well

### ISSUE THREAD

**Issue by rufuspollock** [datasets/house-prices-us#2]
These are now available from drop-down on http://us.spindices.com/index-family/real-estate/sp-case-shiller

**Comment by gradedSystem** [comment]
@rufuspollock link doesn't work and I believe spindices renamed their website to https://www.spice-indices.com/ and now they only have premium section, currently it is better to use https://fred.stlouisfed.org/series which is up-to-date

**Comment by anuveyatsu** [comment]
I believe this is now implemented in https://github.com/datasets/house-prices-us/pull/12
