### ISSUE TITLE
Scraper is no longer working as S&P page has changed

### ISSUE THREAD

**Issue by rgrp** [datasets/house-prices-us#4]
This page has changed:

http://eu.spindices.com/indices/real-estate/sp-case-shiller-us-national-home-price-index

So the find links function has broken:

https://github.com/datasets/house-prices-us/blob/master/scripts/process.py#L20

We need to update the scraper, at least to get the main xls back again.

* [x] fix link extraction
* [x] download files and save to suitable location in `archive/`
* [x] make any changes to scraper to extract the data to the same structure we have in

**Comment by rgrp** [comment]
@zelima I've added a checklist and ticked the items i've done. Note that:

* i have committed the xls files.
* This means you can focus on doing the extract coding and ignore the retrieval for the present (and only reinstate retrieval when you come to commit). This is useful as a) downloading is slow b) it is a bit buggy with some of the downloads timing out.
* xls files seems to have changed structure e.g. national data now is monthly (which is better!) and goes back to 1975. That said not sure home-price-index-levels has changed.

**Comment by rgrp** [comment]
FIXED in PR #9.

/cc @pdehaye maybe worth doing a tweet about this as data not updated in a while :-)

**Comment by pdehaye** [comment]
Done
