### ISSUE TITLE
Running the process.py returns err msg from messytables.py

### ISSUE THREAD

**Issue by fenghaolin** [datasets/house-prices-us#6]
I used python 2.7.10. Running the `python scripts/process.py` gives the following error

> Traceback (most recent call last):
>   File "./scripts/process.py", line 97, in <module>
>     process()
>   File "./scripts/process.py", line 93, in process
>     extract()
>   File "./scripts/process.py", line 79, in extract
>     dataconverters.dataconvert(source, tmp_out, guess_types=False)
>   File "E:\Programs\Anaconda\lib\site-packages\dataconverters__init__.py", line 30, in dataconvert
>     _dataconvert(args)
>   File "E:\Programs\Anaconda\lib\site-packages\dataconverters__init__.py", line 60, in _dataconvert
>     encoding=args.encoding
>   File "E:\Programs\Anaconda\lib\site-packages\dataconverters\xls.py", line 32, in parse
>     table_set = xlsclass(stream, **kwargs)
>   File "E:\Programs\Anaconda\lib\site-packages\messytables\excel.py", line 77, in __init__
>     self.workbook = get_workbook()
>   File "E:\Programs\Anaconda\lib\site-packages\messytables\excel.py", line 50, in get_workbook
>     raise ReadError("Can't read Excel file: %r" % value, traceback)
> messytables.error.ReadError: ('Can\'t read Excel file: XLRDError("Unsupported format, or corrupt file: Expected BOF record; found \'\\xd0\\xcf\\x11\\xe0\\xa1\\xb1\'",)', <traceback object at 0x0000000003C75648>)

I have updated all the required packages such as dataconverters, messytables, xlrd. So, it is probably not the version issue. Is it because I run it on windows 10? Am I supposed to do it only on Unix/Linux like system? Anyone with related information, please let me know. Thanks a lot!

**Comment by rgrp** [comment]
Have you see https://github.com/datasets/house-prices-us/issues/4?

**Comment by fenghaolin** [comment]
Yup. I saw #4 before, but I don't know how the scraper would affect the messytables.py, since messyatables.py was developed outside the scraper. Anyway, thanks a lot.

**Comment by fenghaolin** [comment]
Hi. I saw #4 before, but I didn't (and still don't) think the error is related to #4. I replaced the old process.py with the new one, but the same err msg appears. Is it because I am using windows or because of some other version related issue? My python is 2.7.10 rather than 3.X. Thanks for the help in advance.

**Comment by rgrp** [comment]
Could you pull the latest code and try this again?

**Comment by gradedSystem** [comment]
`dataconverts` and `messytables` currently not going to be used the new scripts so this an old issue 
cc @anuveyatsu
